'''
Created on 02-Jan-2017

@author: ChandraDutt
'''
Cities = ['Vizag', 'Hyderabad', 'Vijayawada', 'Guntur', 'Mumbai', 'Pune', 'Bangalore', 'Mysore', 'Bhuvaneswar', 'Kolkata', 'Chennai', 'Pondicherry', 'Trivandrum', 'New Delhi']

UsersFirstName = ['Chandra','Dhana','Krupa','Sai','Santhosh','Prasad','Shashank','Tarun','Kishore','Ganesh','Steven','Arun','Krishna']
UsersLastName = ['Dutt','Raju','Kumar','Teja','Kalyan']
Suppliers = {'TATA Motors Ltd':'Tatamotors@tataltd.com',
             'Mahindra Motors Ltd':'Motors@mahindra.com',
             'Indian Pictures Ltd':'IndianPictures@gmail.com',
             'Signoraware Plastics':'SignorawarePlastics@rediff.com',
             'Axis Bank':'Axisbank@axispvtbnk.com',
             'HCL Technologies':'Motors@mahindra.com',
             'Walmart':'walmart@gmail.com',
             'Exxon Mobil':'exxonmobil@yahoo.in',
             'Apple Inc.':'AppleInc@apple.com',
             'Berkshire Hathway':'Berkshire@hathway.com',
             'United Health Group':'Unitedhealth@uhg.com',
             'CVS Health':'cvshealth@csv.com',
             'General Motors':'generalmotors@gm.com',
             'Ford Motor':'fordmotors@ford.com',
             'AT&T Inc':'at&t@at&tinc.com',
             'General Electric':'generalelectric@ge.com', 'AmerisourceBergen':'amerisource@bergen.com',
             'Verizon':'verizon@verizon.com',
             'Chevron':'chevron@chevron.com',
             'Costco':'costco@cos.com',
             'Fannie Mae':'fannie@mae.com',
             'Kroger':'kroger@krog.com',
             'Amazon.com':'amazon@ama.com',
             'Walgreens Boots Alliance':'Walgreens@Boots.com',
             'Cardinal Health':'Cardinal@Health.com',
             'Express Scripts Holding':'Express@Scripts.com',
             'J.P. Morgan Chase':'Morgan@Chase.com',
             'Microsoft':'Microsoft@micro.com',
             'Bank of America Corp':'Bank@America.com',
             'Wells Fargo':'Wells@Fargo.com',
             'Home Depot':'Home@Depot.com',
             'Phillips 66':'Phillips@phil.com',
             'Valero Energy':'Valero@Energy.com',
             'Procter & Gamble':'Procter@Gamble.com',
             'State Farm Insurance Cos':'State@FarmCom',
             'Johnson & Johnson':'Johnson@John.com',
             'Archer Daniels Midland':'Archer@Midland',
             'Marathon Petroleum':'Marathon@Petroleum.com',
             'Freddie Mac':'Freddie@Mac.com',
             'United Technologies':'United@Tech.com',
             'Prudential Financial':'Prudential@Financial.com',
             'Cisco Systems':'Cisco@Systems.com',
             'Dow Chemical':'Dow@Chemical.com',
             'Lockheed Martin':'Lockheed@Martin.com',
             'New York Life Insurance':'New@Insurance.com',
             'HCA Holdings':'HCA@Holdings.com',
             'Ingram Micro':'Ingram@Micro.com',
             'Energy Transfer Equity':'Energy@Transfer.com',
             'Tyson Foods':'Tyson@Foods.com',
             'American Airlines Group':'American@Group',
             'Delta Air Lines':'Delta@Lines',
             'Johnson Controls':'Johnson@Controls.com',
             'Best Buy':'Best@Buy.com',
             'Liberty Mutual Insurance Group':'Liberty@Group.com',
             'Goldman Sachs Group':'Goldman@Group.com',
             'Honeywell International':'Honeywell@International.com',
             'Massachusetts Mutual Life Insurance':'Massachusetts@Insurance',
             'Oracle    ':'Oracle@ora.com',
             'Morgan Stanley':'Morgan@Stanley.com',
             'Cigna':'Cigna@cig.com',
             'United Continental Holdings':'United@Holdings.com',
             'INTL FCStone':'INTL@FCStone.com',
             'American Express':'American@Express.com',
             'Gilead Sciences':'Gilead@Sciences.com',
             'Publix Super Markets':'Publix Super@Markets.com',
             'General Dynamics':'General@Dynamics.com',
             'ConocoPhillips':'ConocoPhillips@phil.com',
             'World Fuel Services':'World@Services.com',
             }
